mysite/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'mysite.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^admin/', include(admin.site.urls)),
	url(r'^polls/', include('polls.urls', namespace = "polls")) # namespace ca sa stie comanda {% url polls:... %} in ce app sa se uite sa map-eze adresa url
)

polls/urls.py
from django.conf.urls import patterns, url

from polls import views

urlpatterns = patterns('',
		url(r'^$', views.index, name = 'index'),  #ex /polls/
		url(r'^(?P<poll_id>\d+)/$', views.detail, name = "detail"), # ex /polls/5/		
		url(r'^(?P<poll_id>\d+)/results/$', views.results, name = 'results'), # ex /polls/5/results/
		url(r'^(?P<poll_id>\d+)/vote/$', views.vote, name = "vote"), # ex /polls/5/vote/
	)

myapp/models.py
from django.db import models

# Create your models here.

polls/models.py
from django.db import models
import datetime
from django.utils import timezone
# Create your models here.

class Poll(models.Model):
	question = models.CharField(max_length = 200)
	pub_date = models.DateTimeField('date published')
	
	def __unicode__(self):
		return self.question

	def wasPublishedRecently(self):
		now = timezone.now()
		return now - datetime.timedelta(days = 1) <= self.pub_date < now
				
		#now set some method attributes
	wasPublishedRecently.admin_order_field = 'pub_date'
	wasPublishedRecently.boolean           = True
	wasPublishedRecently.short_description = 'Published recently?'


class Choice(models.Model):
	poll = models.ForeignKey(Poll)
	choice_text = models.CharField(max_length = 200)
	votes = models.IntegerField(default = 0)

	def __unicode__(self):
		return self.choice_text

myapp/views.py
from django.shortcuts import render

# Create your views here.

polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.core.urlresolvers import reverse
#from django.template import RequestContext, loader

from polls.models import Poll, Choice

def index(request):
	latest_poll_list = Poll.objects.order_by('-pub_date')[:5]
	# template = loader.get_template('polls/index.html')
	context = {'latest_poll_list': latest_poll_list} # context is a dictionary mapping template variable names to Python objects
	return render(request, 'polls/index.html', context)
	"""The render() function takes the request object as its first argument,
			   a template name as its second argument 
			   and a dictionary as its optional third argument.
			   It returns an HttpResponse object of the given template
			   rendered with the given context.
	"""

def detail(request, poll_id):
	try:
		poll = Poll.objects.get(pk = poll_id)
	except Poll.DoesNotExist:
		raise Http404
	context = {'poll': poll}
	return render(request, 'polls/detail.html', context) 


def results(request, poll_id):
	poll = get_object_or_404(Poll, pk = poll_id)
	context = {'poll': poll}
	return render(request, 'polls/results.html', context)


def vote(request, poll_id):
	try:
		p = Poll.objects.get(pk = poll_id)
	except Poll.DoesNotExist:
		raise Http404
	try:
		selected_choice = p.choice_set.get(pk = request.POST['choice'])
		# request.POST['choice'] returns the ID of the selected choice, 
		# as a string. request.POST values are always strings.
	except (KeyError, Choice.DoesNotExist):
		#redisplay the poll voting form
		return render(request, 'polls/detail.html', {
			'poll': p,
			'error_message': "You didn't select a choice."
			})
	else:
		selected_choice.votes += 1
		selected_choice.save()
		# Always return an HttpResponseRedirect after successfully dealing 
		# with POST data. This prevents data from being posted twice if a user 
		# user hits the Black button.
		return HttpResponseRedirect(reverse('polls:results', args=(p.id,)))
		# reverse() function helps avoid having to hardcode a URL in the view function
		# reverse() returns something like '/polls/3/results/'



# Create your views here.

polls/templates/polls/detail.html
<h1> {{ poll.question }} </h1>

{% if error_message %}
	<p> <strong> {{ error.message }} </strong> </p>
{% endif %}

<form action = "{% url 'polls:vote' poll.id %}" method = "post">
{% csrf_token %}
{% for choice in poll.choice_set.all %}
	<input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
	<label for="choice{{ forloop.counter }}">
		{{ choice.choice_text }}
	</label>
	<br />
{% endfor %}
<input type="submit" value="Vote" />
</form>

<br/> <br/>

<form action="{% url 'polls:index' %}" method="post">
{% csrf_token %}
	<input type="submit" value="Go to Home">
</form>

polls/templates/polls/index.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />


{% if latest_poll_list %}
	<ul>
		{% for poll in latest_poll_list %}
		<li> <a href="{% url 'polls:detail' poll.id %}">{{ poll.question }}</a> </li>
						<!-- acel polls este namespace-ul din mysite/urls.py
						   	 iar detail este numele din polls/urls.py, si ii dam parametrul poll.id 
						  -->
		{% endfor %}
	</ul>
{% else %}
	<p> No polls are available. </p>
{% endif %}

polls/templates/polls/results.html
<h1> {{ poll.question }} </h1>

<ul>
{% for choice in poll.choice_set.all %}
	<li> {{ choice.choice_text }} -- {{ choice.votes }} vote {{ choice.votes|pluralize }} </li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' poll.id %}">Vote again?</a>